version: 1.0.{build}
build_script:
- ps: >-
    dotnet build -c Release

    dotnet pack -c Release
test_script:
- ps: >-
    cd .\test\SimonTaite.Extensions.Test.Unit

    dotnet test
deploy:
- provider: NuGet
  api_key:
    secure: uUDcL9MCWdtapIZZSi6h6nvNEU+/erzsl5GH7T/tthQp6Le4xtK55XcDkuyoq8VV
  artifact: src\*\bin\Release\*.nupkg
  on:
    branch: master